trigger:
  branches:
    include:
      - develop
      - master
      - release/*
  paths:
    include:
      - Caching/*

pr:
  branches:
    include:
      - develop
      - master
      - release/*
  paths:
    include:
      - Caching/*

variables:
  OrganizationName: UiPath
  BuildDefinitionName: $(Build.DefinitionName)
  ProjectShortName: Caching
  ProjectName: Caching
  GitVersion.SemVer: ''

stages:
  - stage: 'CI'
    jobs:
    - job: BuildAndRunTests
      displayName: Build & Run tests
      pool:
        vmImage: ubuntu-latest
      variables:
        BuildConfiguration: Release
        Solution: "$(Build.SourcesDirectory)/Caching/Caching.sln"
        ArtifactsOutputPath: Packages
        Build.Repository.Clean: true
        build_counter: $[counter('build_counter_1_0_0', 1)]

      steps:
      - task: gitversion/setup@0
        displayName: 'Setup GitVersion'
        inputs:
          versionSpec: '5.x'
      
      - task: gitversion/execute@0
        displayName: 'Execute GitVersion'
        inputs:
          runtime: 'core'
          useConfigFile: true
          configFilePath: '$(Build.SourcesDirectory)/Caching/GitVersion.yml'
          additionalArguments: '/output json /output buildserver /updateassemblyinfo \"$(Build.SourcesDirectory)/Caching/GlobalAssemblyInfo.cs\"'

      - pwsh: |
          $semVer = $env:GITVERSION_NUGETVERSION
          $buildNumber = "$(Build.BuildNumber)"
          if (("$(Build.SourceBranch)" -match "^refs/heads/release/*") -or ("$(Build.SourceBranch)" -eq "refs/heads/master")) {
            $buildNumber = $semVer + "." + $env:BUILD_COUNTER
          } else {
            $semVer += '-' + $env:BUILD_COUNTER
            $buildNumber += "." + $env:BUILD_COUNTER
          }
          Write-Host "SemVer: $semVer"
          Write-Host "BuildNumber: $buildNumber"
          Write-Host "##vso[build.updatebuildnumber]$buildNumber"
          Write-Host "##vso[task.setvariable variable=PackageVersion;]$semVer"
        displayName: "Adjust build number to ensure package unique name"

      - pwsh: |
          Write-Host "Variables for current build:"
          Get-ChildItem ENV:*
        displayName: Print variables
        continueOnError: true
        condition: always()

      - task: UseDotNet@2
        displayName: Use .NET 6 SDK
        inputs:
          packageType: sdk
          version: 6.x
          includePreviewVersions: false
          performMultiLevelLookup: true

      - task: UseDotNet@2
        displayName: Use .NET 8 SDK
        inputs:
          packageType: sdk
          version: 8.x
          useGlobalJson: true
          includePreviewVersions: false
          performMultiLevelLookup: true

      - pwsh: |
          if (!(dotnet tool list -g | Where-Object {$_.contains("dotnet-coverage")})){
            dotnet tool install --global dotnet-coverage --version 17.11.3
          } else {
            dotnet tool update --global dotnet-coverage --version 17.11.3
          }

          dotnet --info
          dotnet tool list -g
        displayName: Install dotnet tools
        retryCountOnTaskFailure: 10

      - task: NuGetToolInstaller@0
        displayName: Use NuGet 6.x
        inputs:
          versionSpec: '6.x'

      - task: NuGetAuthenticate@1
        displayName: Authenticate to NuGet

      - task: NuGetCommand@2
        displayName: "Restore Nuget packages"
        inputs:
          command: restore
          restoreSolution: $(Solution)
          feedsToUse: config
          nugetConfigPath: "$(Build.SourcesDirectory)/Caching/NuGet.Config"

      - task: SonarCloudPrepare@2
        inputs:
          SonarCloud: SonarConnection
          organization: ui
          scannerMode: MSBuild
          projectKey: UiPath_ServiceCommon-Caching
          projectName: UiPath_ServiceCommon-Caching
          projectVersion: '$(PackageVersion)'
          extraProperties: |
            sonar.sourceEncoding=UTF-8
            sonar.verbose=false
            sonar.log.level=Info
            sonar.exclusions=**/*AssemblyInfo.cs,**/*.js,**/*.css,**/*.scss,**/*.ts,**/*.json,**/*.config,**/*.resx
            sonar.cs.vscoveragexml.reportsPaths=$(Agent.TempDirectory)/**/coverage.xml
            sonar.cs.file.suffixes=.cs
            sonar.cs.analyzeGeneratedCode=false
            sonar.dotnet.excludeTestProjects=true

      - task: DotNetCoreCLI@2
        displayName: "Build Solution"
        inputs:
          command: build
          projects: $(Solution)
          arguments: >
            --configuration $(BuildConfiguration)
            --no-restore
            --no-incremental
            /p:Company=$(OrganizationName)
            /p:SignAssembly=false
            /p:IgnoreCollectDist=false
            /p:GetVersion=false
            /p:GenerateGitVersionInformation=false
            /p:UpdateVersionProperties=false

      - pwsh: |
          dotnet-coverage collect "dotnet test --verbosity normal" -f xml -o "$(Agent.TempDirectory)/test-results/coverage.xml"
        displayName: 'Run tests'
        workingDirectory: $(Build.SourcesDirectory)/Caching

      - task: SonarCloudAnalyze@2

      - task: SonarCloudPublish@2
        inputs:
          pollingTimeoutSec: '300'

      - task: DotNetCoreCLI@2
        displayName: "Create Package"
        inputs:
          command: pack
          packagesToPack: "**/Caching.*.csproj;"
          versioningScheme: byEnvVar
          versionEnvVar: 'PackageVersion'
          nobuild: true
          includeSymbols: false
          outputDir: $(ArtifactsOutputPath)
        condition: succeeded()

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          ArtifactName: Caching
          PathtoPublish: "$(Build.SourcesDirectory)/$(ArtifactsOutputPath)"

  - stage: 'FEATURE'
    dependsOn: [ 'CI' ]
    condition: and(
        succeeded(), 
        ne(variables['Build.SourceBranch'], 'refs/heads/develop'), 
        ne(variables['Build.SourceBranch'], 'refs/heads/master'),
        ne(startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), 'true')
      )
    jobs:
      - deployment: 'PublishPackageToFeature'
        displayName: 'Publish to feature feed'
        environment: FEATURE
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: push
                    packagesToPush: '$(Agent.BuildDirectory)/Caching/*.nupkg'
                    publishVstsFeed: '1d71f16a-8504-4895-a839-687a1a4819d4'

  - stage: 'ALPHA'
    dependsOn: [ 'CI' ]
    condition: and(
        succeeded(), 
        eq(variables['Build.SourceBranch'], 'refs/heads/develop') 
      )
    jobs:
      - deployment: 'PublishPackageToAlpha'
        displayName: 'Publish to alpha feed'
        environment: ALPHA
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: push
                    packagesToPush: '$(Agent.BuildDirectory)/Caching/*.nupkg'
                    publishVstsFeed: '1d71f16a-8504-4895-a839-687a1a4819d4'

  - stage: 'BETA'
    dependsOn: [ 'CI' ]
    condition: and(
        succeeded(), 
        eq(variables['Build.SourceBranch'], 'refs/heads/master')
      )
    jobs:
      - deployment: 'PublishPackageToBeta'
        displayName: 'Publish to beta feed'
        environment: BETA
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: push
                    packagesToPush: '$(Agent.BuildDirectory)/Caching/*.nupkg'
                    publishVstsFeed: '1d71f16a-8504-4895-a839-687a1a4819d4'

  - stage: 'RELEASE'
    dependsOn: [ 'CI' ]
    condition: and(
        succeeded(), 
        startsWith(variables['Build.SourceBranch'], 'refs/heads/release')
      )
    jobs:
      - deployment: 'PublishPackageToRelease'
        displayName: 'Publish to release feed'
        environment: RELEASE
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: push
                    packagesToPush: '$(Agent.BuildDirectory)/Caching/*.nupkg'
                    publishVstsFeed: 'a7f75525-c998-47e3-8aaf-0396542795c9'
