using UiPath.Caching.Tests.Fakes;

namespace UiPath.Caching.Tests.Locking;

/// <summary>A batch joins the generator runs already in flight for its keys, and runs its own generator for the rest.</summary>
public class BatchJoinTests
{
    private static readonly TimeSpan LockTimeout = TimeSpan.FromMilliseconds(50);

    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    private static InMemoryCacheOptions Options => new() { LocalLockTimeout = LockTimeout };

    [Fact]
    public async Task A_batch_whose_keys_overlap_a_running_batch_joins_the_shared_keys_and_generates_the_rest()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var first = new SlowBatch();
        var second = new SlowBatch { Releasing = true };

        var held = Run(cache, ["k1", "k2"], first.Generate, Ct);
        await first.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var overlapping = Run(cache, ["k2", "k3"], second.Generate, Ct);
        await second.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        await Task.Delay(200, Ct);

        overlapping.IsCompleted.Should().BeFalse("k2 is still being generated by the first batch");
        second.Requested.Should().Equal("k3");
        first.Release.SetResult();

        (await held).Select(p => p.Value).Should().Equal("v:k1", "v:k2");
        (await overlapping).Select(p => p.Value).Should().Equal("v:k2", "v:k3");
        first.Requested.Should().Equal("k1", "k2");
    }

    [Fact]
    public async Task A_batch_that_waits_out_the_lock_joins_every_key_in_flight_and_runs_no_generator()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var first = new SlowBatch();
        var second = new SlowBatch();

        var held = Run(cache, ["k1", "k2"], first.Generate, Ct);
        await first.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var waiter = Run(cache, ["k1", "k2"], second.Generate, Ct);
        await Task.Delay(400, Ct);

        waiter.IsCompleted.Should().BeFalse();
        first.Release.SetResult();

        (await waiter).Select(p => p.Value).Should().Equal("v:k1", "v:k2");
        (await held).Should().HaveCount(2);
        second.Calls.Should().Be(0);
        first.Calls.Should().Be(1);
    }

    [Fact]
    public async Task A_failed_run_fails_the_batches_that_joined_it()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var first = new SlowBatch();
        var second = new SlowBatch { Releasing = true };

        var held = Run(cache, ["k1", "k2"], first.Generate, Ct);
        await first.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var overlapping = Run(cache, ["k2", "k3"], second.Generate, Ct);
        await second.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        first.Fail.SetResult();

        await ((Func<Task>)(() => held)).Should().ThrowAsync<InvalidOperationException>();
        await ((Func<Task>)(() => overlapping)).Should().ThrowAsync<InvalidOperationException>();
        (await Run(cache, ["k2"], new SlowBatch { Releasing = true }.Generate, Ct)).Single().Value.Should().Be("v:k2", "the next batch starts a new run");
    }

    [Fact]
    public async Task A_batch_that_cancels_stops_waiting_and_leaves_the_run_to_its_starter()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var first = new SlowBatch();
        var second = new SlowBatch { Releasing = true };
        using var cancellation = CancellationTokenSource.CreateLinkedTokenSource(Ct);

        var held = Run(cache, ["k1", "k2"], first.Generate, Ct);
        await first.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var overlapping = Run(cache, ["k2"], second.Generate, cancellation.Token);
        await Task.Delay(200, Ct);
        await cancellation.CancelAsync();

        await ((Func<Task>)(() => overlapping)).Should().ThrowAsync<OperationCanceledException>();
        first.Release.SetResult();
        (await held).Should().HaveCount(2);
    }

    [Fact]
    public async Task A_batch_whose_starter_cancelled_generates_the_keys_it_had_joined_itself()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var first = new SlowBatch();
        var second = new SlowBatch { Releasing = true };
        using var starterCancellation = CancellationTokenSource.CreateLinkedTokenSource(Ct);

        var held = Run(cache, ["k1", "k2"], first.Generate, starterCancellation.Token);
        await first.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var overlapping = Run(cache, ["k2", "k3"], second.Generate, Ct);
        await second.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        await starterCancellation.CancelAsync();

        await ((Func<Task>)(() => held)).Should().ThrowAsync<OperationCanceledException>();
        (await overlapping).Select(p => p.Value).Should().Equal("v:k2", "v:k3");
        second.Requested.Should().Contain("k2");
    }

    [Fact]
    public async Task A_batch_joins_a_single_key_run_in_flight()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var release = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        var started = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        var second = new SlowBatch { Releasing = true };

        async Task<string?> Slow(CancellationToken _)
        {
            started.TrySetResult();
            await release.Task;
            return "single";
        }

        var single = Task.Run(async () => await cache.GetOrAddAsync("k2", Slow, (CachePolicy?)null, Ct), Ct);
        await started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var batch = Run(cache, ["k2", "k3"], second.Generate, Ct);
        await second.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        await Task.Delay(200, Ct);
        batch.IsCompleted.Should().BeFalse();
        release.SetResult();

        (await batch).Select(p => p.Value).Should().Equal("single", "v:k3");
        second.Requested.Should().Equal("k3");
        (await single).Should().Be("single");
    }

    [Fact]
    public async Task A_single_key_call_joins_the_batch_run_generating_its_key()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var batch = new SlowBatch();
        var singleCalls = 0;

        var held = Run(cache, ["k1", "k2"], batch.Generate, Ct);
        await batch.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var single = Single(cache, "k2", _ => { Interlocked.Increment(ref singleCalls); return Task.FromResult<string?>("single"); }, Ct);
        await Task.Delay(300, Ct);

        single.IsCompleted.Should().BeFalse("k2 is being generated by the batch");
        batch.Release.SetResult();

        (await single).Should().Be("v:k2");
        (await held).Should().HaveCount(2);
        singleCalls.Should().Be(0);
    }

    [Fact]
    public async Task A_batch_failure_reaches_the_single_key_call_that_joined_it()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var batch = new SlowBatch();

        var held = Run(cache, ["k1", "k2"], batch.Generate, Ct);
        await batch.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var single = Single(cache, "k2", _ => Task.FromResult<string?>("single"), Ct);
        await Task.Delay(300, Ct);
        batch.Fail.SetResult();

        await ((Func<Task>)(() => held)).Should().ThrowAsync<InvalidOperationException>();
        await ((Func<Task>)(() => single)).Should().ThrowAsync<InvalidOperationException>();
    }

    [Fact]
    public async Task A_single_key_call_that_cancels_stops_waiting_for_the_batch()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var batch = new SlowBatch();
        using var cancellation = CancellationTokenSource.CreateLinkedTokenSource(Ct);

        var held = Run(cache, ["k1", "k2"], batch.Generate, Ct);
        await batch.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var single = Single(cache, "k2", _ => Task.FromResult<string?>("single"), cancellation.Token);
        await Task.Delay(300, Ct);
        await cancellation.CancelAsync();

        await ((Func<Task>)(() => single)).Should().ThrowAsync<OperationCanceledException>();
        batch.Release.SetResult();
        (await held).Should().HaveCount(2);
    }

    [Fact]
    public async Task A_single_key_call_generates_itself_when_the_batch_that_started_the_run_cancels()
    {
        using var cache = InMemoryMultilayer.Cache(Options);
        var batch = new SlowBatch();
        using var starterCancellation = CancellationTokenSource.CreateLinkedTokenSource(Ct);

        var held = Run(cache, ["k1", "k2"], batch.Generate, starterCancellation.Token);
        await batch.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var single = Single(cache, "k2", _ => Task.FromResult<string?>("single"), Ct);
        await Task.Delay(300, Ct);
        await starterCancellation.CancelAsync();

        await ((Func<Task>)(() => held)).Should().ThrowAsync<OperationCanceledException>();
        (await single).Should().Be("single");
    }

    [Fact]
    public async Task Without_the_local_lock_batches_still_generate_their_own_keys()
    {
        using var cache = InMemoryMultilayer.Cache(new InMemoryCacheOptions { LocalLockEnabled = false });
        var first = new SlowBatch();
        var second = new SlowBatch { Releasing = true };

        var held = Run(cache, ["k1", "k2"], first.Generate, Ct);
        await first.Started.Task.WaitAsync(TimeSpan.FromSeconds(10), Ct);
        var overlapping = await Run(cache, ["k2", "k3"], second.Generate, Ct);

        overlapping.Select(p => p.Value).Should().Equal("v:k2", "v:k3");
        second.Requested.Should().Equal("k2", "k3");
        first.Release.SetResult();
        await held;
    }

    private static Task<string?> Single(MultilayerCache cache, string key, Func<CancellationToken, Task<string?>> generator, CancellationToken token) =>
        Task.Run(async () => await cache.GetOrAddAsync(key, generator, (CachePolicy?)null, token), Ct);

    private static Task<KeyValuePair<string, string?>[]> Run(MultilayerCache cache, string[] keys, Func<string[], CancellationToken, Task<KeyValuePair<string, string?>[]>> generator, CancellationToken token) =>
        Task.Run(async () => await cache.GetOrAddAsync<string, string>(keys.Select(k => new KeyValuePair<CacheKey, string>(k, k)).ToArray(), generator, (CachePolicy?)null, token), Ct);

    private sealed class SlowBatch
    {
        private int _calls;

        public bool Releasing { get; init; }

        public TaskCompletionSource Started { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);

        public TaskCompletionSource Release { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);

        public TaskCompletionSource Fail { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);

        public List<string> Requested { get; } = [];

        public int Calls => Volatile.Read(ref _calls);

        public async Task<KeyValuePair<string, string?>[]> Generate(string[] states, CancellationToken token)
        {
            Interlocked.Increment(ref _calls);
            lock (Requested)
            {
                Requested.AddRange(states);
            }

            Started.TrySetResult();
            if (!Releasing)
            {
                var finished = await Task.WhenAny(Release.Task, Fail.Task, Task.Delay(Timeout.Infinite, token)).ConfigureAwait(false);
                token.ThrowIfCancellationRequested();
                if (finished == Fail.Task)
                {
                    throw new InvalidOperationException("the load failed");
                }
            }

            return [.. states.Select(s => new KeyValuePair<string, string?>(s, "v:" + s))];
        }
    }
}
